/**
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║  PROPRIETARY AND CONFIDENTIAL — ALL RIGHTS RESERVED                     ║
 * ║  © 2024-2026 Omar Mohammad Abunadi™ | QuranChain™                       ║
 * ║  Immutable Founder Royalty: 30% · License: See /LICENSE                  ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 */
/**
 * Platform configurations for all QuranChain ecosystem websites
 * Each config drives a full subdomain website via PlatformSite.jsx
 * Subdomains: {platform}.darcloud.host
 */

export const PLATFORMS = {
  darcloud: {
    name: 'DarCloud™',
    subdomain: 'darcloud',
    domain: 'darcloud.host',
    icon: '☁️',
    bgGradient: 'from-blue-950 via-indigo-950 to-slate-950',
    heroGradient: 'from-blue-600 to-indigo-600',
    ctaGradient: 'from-blue-600 to-indigo-600',
    keywords: ['darcloud'],
    headline: 'Cloud Hosting Built on Islamic Values',
    subheadline: 'Enterprise-grade Sharia-compliant cloud infrastructure spanning 60+ global cities. Hosting, domains, storage, CDN, email, and blockchain services — all in one platform.',
    featuresTitle: 'Everything You Need in the Cloud',
    featuresSubtitle: 'From web hosting to AI deployment, DarCloud powers the entire QuranChain ecosystem',
    features: [
      { icon: '🌐', title: 'Web Hosting', description: 'NVMe SSD hosting with 99.99% uptime SLA. Starter to Enterprise tiers with auto-scaling and load balancing.' },
      { icon: '🔒', title: 'Domain Registration', description: 'Register .com, .net, .org, .io, .dev, .app, .host, and .cloud domains with WHOIS privacy protection.' },
      { icon: '💾', title: 'Cloud Storage', description: 'Encrypted cloud storage with RAID-10 redundancy. Personal Cloud plans and pay-as-you-go options.' },
      { icon: '⚡', title: 'CDN Distribution', description: 'Global content delivery network with edge caching across 200+ PoPs for lightning-fast load times.' },
      { icon: '📧', title: 'Business Email', description: 'Professional email hosting with spam filtering, encryption, and custom domain support.' },
      { icon: '🤖', title: 'AI Agent School', description: 'Deploy and train AI agents on dedicated GPU instances with blockchain-verified training records.' },
    ],
    ctaTitle: 'Deploy Your Vision Today',
    ctaDescription: 'Join thousands of businesses running on Sharia-compliant cloud infrastructure with 24/7 support.',
  },

  meshtalk: {
    name: 'MeshTalk™',
    subdomain: 'meshtalk',
    domain: 'meshtalk.darcloud.host',
    icon: '📡',
    bgGradient: 'from-purple-950 via-violet-950 to-slate-950',
    heroGradient: 'from-purple-600 to-violet-600',
    ctaGradient: 'from-purple-600 to-violet-600',
    keywords: ['meshtalk'],
    headline: 'The Decentralized Cellular Network',
    subheadline: 'MeshTalk OS powers cellular, WiFi, Bluetooth, LoRa, ZigBee, and FM radio through a unified mesh protocol. Phone plans, internet, IoT, and enterprise communications.',
    featuresTitle: 'Beyond Traditional Telecom',
    featuresSubtitle: 'Multi-protocol mesh networking that works even when the grid goes down',
    features: [
      { icon: '📱', title: 'Cell Plans', description: 'Personal, Family, and Business cellular plans with unlimited talk, text, and data on our mesh network.' },
      { icon: '🌐', title: 'Home Internet', description: 'Fiber-speed broadband through mesh routing. Basic, Premium, and Business tiers available.' },
      { icon: '📻', title: 'MeshTalk OS', description: 'Open-source protocol stack: Open5G, WiFi 6, Bluetooth 5.2, LoRa, ZigBee, and FM radio — all in one OS.' },
      { icon: '🏢', title: 'Cloud PBX', description: 'Enterprise phone system with auto-attendant, voicemail, conferencing, and CRM integration.' },
      { icon: '🛰️', title: 'IoT Gateway', description: 'Connect thousands of IoT devices through mesh routing with real-time analytics and alerts.' },
      { icon: '🌍', title: 'Global Roaming', description: 'International calling, data roaming, and roaming packs across 190+ countries.' },
    ],
    ctaTitle: 'Own Your Communications',
    ctaDescription: 'Decentralized, encrypted, unstoppable. MeshTalk works peer-to-peer when infrastructure fails.',
  },

  whispernet: {
    name: 'WhisperNet™',
    subdomain: 'whispernet',
    domain: 'whispernet.darcloud.host',
    icon: '🔐',
    bgGradient: 'from-gray-950 via-zinc-950 to-slate-950',
    heroGradient: 'from-gray-600 to-zinc-600',
    ctaGradient: 'from-gray-700 to-zinc-800',
    keywords: ['whispernet'],
    headline: 'Encrypted Everything. Zero Surveillance.',
    subheadline: 'Military-grade encrypted communications, VPN, anonymous email, secure file vault, and mesh relay nodes. Your digital sovereignty, guaranteed.',
    featuresTitle: 'Privacy is a Human Right',
    featuresSubtitle: 'End-to-end encryption across all channels — even we cannot read your data',
    features: [
      { icon: '🛡️', title: 'Stealth VPN', description: 'Multi-hop VPN with obfuscation that bypasses deep packet inspection. Personal, Business, and Enterprise tiers.' },
      { icon: '📧', title: 'Anonymous Email', description: 'Zero-knowledge email with PGP encryption, disposable aliases, and no IP logging.' },
      { icon: '🔒', title: 'Secure File Vault', description: 'AES-256 encrypted storage with zero-knowledge architecture. Only you hold the keys.' },
      { icon: '📞', title: 'Secure Voice', description: 'End-to-end encrypted voice calls over mesh network. No metadata collection.' },
      { icon: '🌐', title: 'Mesh Relay Node', description: 'Run a WhisperNet relay node to strengthen the privacy network and earn QCOIN rewards.' },
      { icon: '🔑', title: 'E2E Messaging', description: 'Signal-protocol messaging with forward secrecy, disappearing messages, and screenshot protection.' },
    ],
    ctaTitle: 'Take Back Your Privacy',
    ctaDescription: 'In a world of surveillance, WhisperNet is your shield. Zero logs. Zero compromise.',
  },

  daralnas: {
    name: 'Dar Al-Nas™',
    subdomain: 'daralnas',
    domain: 'daralnas.darcloud.host',
    icon: '🏦',
    bgGradient: 'from-amber-950 via-yellow-950 to-slate-950',
    heroGradient: 'from-amber-600 to-yellow-600',
    ctaGradient: 'from-amber-600 to-yellow-600',
    keywords: ['dar al-nas', 'muslim wallet'],
    headline: 'Islamic Banking. Reimagined.',
    subheadline: 'Sharia-compliant savings, checking, mortgages, Takaful insurance, Zakat automation, healthcare, real estate, and the Muslim Wallet — all on blockchain.',
    featuresTitle: 'Complete Islamic Financial Services',
    featuresSubtitle: 'Certified by 3 independent Sharia scholars. Every transaction blockchain-verified.',
    features: [
      { icon: '💰', title: 'Banking', description: 'Savings (Mudarabah), Current, Investment, Premium, and Business accounts with halal profit-sharing.' },
      { icon: '🏠', title: 'Halal Mortgages', description: 'Murabaha home financing with transparent cost-plus-profit. No interest, fixed payments, up to $2M.' },
      { icon: '🛡️', title: 'Takaful Insurance', description: 'Cooperative insurance: Health, Auto, Life, Property, and Business. Surplus shared among members.' },
      { icon: '💳', title: 'Debit Cards', description: 'Stripe Issuing cards with halal merchant filtering. Standard, Premium Metal, Virtual, and Prepaid options.' },
      { icon: '📱', title: 'Muslim Wallet', description: 'Mobile banking app with Zakat calculator, Sadaqah donations, Waqf endowments, and crypto integration.' },
      { icon: '🏥', title: 'Healthcare', description: 'Telehealth consultations and healthcare plans through our halal-verified provider network.' },
    ],
    ctaTitle: 'Banking Without Riba',
    ctaDescription: 'Halal finance is not just possible — it is profitable. Join the Islamic financial revolution.',
  },

  logistics: {
    name: 'OliveAir & OliveSea™',
    subdomain: 'logistics',
    domain: 'logistics.darcloud.host',
    icon: '✈️',
    bgGradient: 'from-green-950 via-emerald-950 to-slate-950',
    heroGradient: 'from-green-600 to-emerald-600',
    ctaGradient: 'from-green-600 to-emerald-600',
    keywords: ['oliveair', 'olivesea', 'dar logistics'],
    headline: 'Global Logistics. Halal Supply Chains.',
    subheadline: 'Air freight, maritime shipping, last-mile delivery, 3PL integration, customs clearance, and blockchain-verified halal supply chain tracking — worldwide.',
    featuresTitle: 'End-to-End Logistics Platform',
    featuresSubtitle: 'From manufacturer to doorstep, every shipment tracked on blockchain',
    features: [
      { icon: '✈️', title: 'OliveAir Freight', description: 'Air cargo brokering, dispatch optimization, fleet management, and dynamic pricing across 500+ routes.' },
      { icon: '🚢', title: 'OliveSea Maritime', description: 'Container shipping (20ft/40ft FCL), LCL consolidation, bulk cargo, refrigerated, and dangerous goods.' },
      { icon: '🚚', title: 'Last-Mile Delivery', description: 'Same-day and next-day delivery with real-time tracking, proof of delivery, and returns processing.' },
      { icon: '🏭', title: 'Dar Logistics', description: 'Warehousing, global shipping, halal supply chain certification, and multimodal transport management.' },
      { icon: '📊', title: 'Supply Chain Analytics', description: 'Real-time visibility, predictive analytics, demand forecasting, and route optimization AI.' },
      { icon: '🔗', title: 'Blockchain Tracking', description: 'Immutable cargo tracking from origin to destination with halal certification at every checkpoint.' },
    ],
    ctaTitle: 'Ship Anything. Anywhere. Halal.',
    ctaDescription: 'The only logistics platform with built-in halal supply chain verification.',
  },

  blockchain: {
    name: 'QuranChain Blockchain™',
    subdomain: 'blockchain',
    domain: 'blockchain.darcloud.host',
    icon: '⛓️',
    bgGradient: 'from-orange-950 via-red-950 to-slate-950',
    heroGradient: 'from-orange-600 to-red-600',
    ctaGradient: 'from-orange-600 to-red-600',
    keywords: ['layer 1', 'validator', 'full node', 'rpc', 'gas toll', 'bridge', 'stak', 'smart contract', 'govern', 'defi', 'block explorer', 'analy', 'aml', 'fraud', 'multi-sig', 'ibc', 'cosmwasm', 'chain upgrade', 'enterprise blockchain', 'private chain', 'revenue track', 'consulting', 'global validator', 'validator managed'],
    headline: 'The Sharia Layer 1 Blockchain',
    subheadline: 'Built on Cosmos SDK with Tendermint BFT consensus. Run validators, deploy smart contracts, bridge across 47+ chains, and participate in governance.',
    featuresTitle: 'Enterprise-Grade Blockchain Infrastructure',
    featuresSubtitle: 'The only Layer 1 blockchain certified Sharia-compliant by independent scholars',
    features: [
      { icon: '🔗', title: 'Layer 1 Nodes', description: 'Run full nodes with Cosmos SDK, Tendermint BFT, CosmWasm smart contracts, and IBC communication.' },
      { icon: '✅', title: 'Validators', description: 'Stake QURAN tokens, produce blocks, earn 5% APR. Standard, Enterprise, and Managed hosting options.' },
      { icon: '🌉', title: 'Cross-Chain Bridge', description: 'Bridge assets across 47+ blockchain networks with atomic swaps and liquidity pools.' },
      { icon: '📊', title: 'DeFi Protocols', description: 'Liquidity provision, yield optimization, token swaps — all Sharia-screened and halal-verified.' },
      { icon: '🔍', title: 'Block Explorer', description: 'Real-time transaction monitoring, analytics dashboard, and revenue tracking API.' },
      { icon: '🛡️', title: 'Security Suite', description: 'AML/KYC compliance, fraud detection AI, multi-sig wallets, and smart contract audits.' },
    ],
    ctaTitle: 'Build on QuranChain',
    ctaDescription: 'The most advanced Sharia-compliant blockchain. Deploy your vision on immutable infrastructure.',
  },

  qex: {
    name: 'QEX Exchange™',
    subdomain: 'qex',
    domain: 'qex.darcloud.host',
    icon: '📊',
    bgGradient: 'from-cyan-950 via-blue-950 to-slate-950',
    heroGradient: 'from-cyan-600 to-blue-600',
    ctaGradient: 'from-cyan-600 to-blue-600',
    keywords: ['qex'],
    headline: 'Trade Halal. Trade Smart.',
    subheadline: 'The decentralized exchange for Sharia-screened tokens. Trade QURAN, QCOIN, QLEARN and 50+ vetted assets with advanced tools and low fees.',
    featuresTitle: 'Professional Trading Platform',
    featuresSubtitle: 'Every listed token screened by our Sharia board',
    features: [
      { icon: '📈', title: 'Spot Trading', description: 'Market, limit, and stop orders with real-time order books. Basic to Institutional tiers.' },
      { icon: '🖼️', title: 'NFT Marketplace', description: 'Mint, trade, and collect NFTs. AI Agent License NFTs, Islamic art, and digital collectibles.' },
      { icon: '🤖', title: 'Algo Trading', description: 'REST and WebSocket APIs for algorithmic trading bots with priority order execution.' },
      { icon: '💹', title: 'Market Making', description: 'Provide liquidity and earn rewards through our market maker program with rebate incentives.' },
      { icon: '📋', title: 'Token Listing', description: 'List your Sharia-compliant token on QEX with our streamlined listing and vetting process.' },
      { icon: '📊', title: 'Advanced Charts', description: 'TradingView integration with 100+ technical indicators and real-time PnL analytics.' },
    ],
    ctaTitle: 'Start Trading Today',
    ctaDescription: 'Low fees. Halal listings. Professional tools. The exchange built for Islamic finance.',
  },

  darpay: {
    name: 'DarPay™',
    subdomain: 'darpay',
    domain: 'darpay.darcloud.host',
    icon: '💳',
    bgGradient: 'from-pink-950 via-rose-950 to-slate-950',
    heroGradient: 'from-pink-600 to-rose-600',
    ctaGradient: 'from-pink-600 to-rose-600',
    keywords: ['darpay'],
    headline: 'Accept Crypto. Settle in Fiat.',
    subheadline: 'Payment processing for the blockchain era. Accept Bitcoin, Ethereum, USDT, and all QuranChain tokens with instant fiat settlement.',
    featuresTitle: 'Payments Made Simple',
    featuresSubtitle: 'The bridge between crypto and traditional commerce',
    features: [
      { icon: '💰', title: 'Merchant Payments', description: 'Accept 90+ cryptocurrencies with checkout widgets, QR codes, and API integration. 1% processing fee.' },
      { icon: '🔄', title: 'Crypto-to-Fiat Bridge', description: 'Instant conversion and settlement to Dar Al-Nas banking or any supported bank account.' },
      { icon: '📄', title: 'Invoice Processing', description: 'Create and send invoices with crypto payment options. Auto-conversion and reconciliation.' },
      { icon: '🛒', title: 'E-Commerce Plugins', description: 'WooCommerce, Shopify, and custom API integrations for seamless checkout experiences.' },
      { icon: '🌍', title: 'Multi-Chain Support', description: 'Ethereum, BSC, Polygon, Solana, Cosmos, and 40+ more chains monitored in real-time.' },
      { icon: '📊', title: 'Analytics Dashboard', description: 'Transaction volume, conversion rates, settlement tracking, and tax reporting exports.' },
    ],
    ctaTitle: 'Accept Crypto Payments Today',
    ctaDescription: 'Join 10,000+ merchants accepting crypto with automatic halal compliance verification.',
  },

  tokens: {
    name: 'QuranChain Tokens™',
    subdomain: 'tokens',
    domain: 'tokens.darcloud.host',
    icon: '🪙',
    bgGradient: 'from-yellow-950 via-amber-950 to-slate-950',
    heroGradient: 'from-yellow-500 to-amber-600',
    ctaGradient: 'from-yellow-500 to-amber-600',
    keywords: ['quran token', 'qcoin token', 'qlearn token', 'ecosystem token'],
    headline: 'The Tokens Powering the Ecosystem',
    subheadline: 'QURAN (Layer 1 native), QCOIN (utility), QLEARN (AI education), and Ecosystem Token Packs — the digital assets driving Islamic innovation.',
    featuresTitle: 'Token Ecosystem',
    featuresSubtitle: 'Each token serves a specific purpose in the QuranChain economy',
    features: [
      { icon: '🕌', title: 'QURAN Token', description: 'Native Layer 1 token for staking, governance, gas fees, and cross-chain bridging. $50.00/QURAN.' },
      { icon: '💎', title: 'QCOIN Token', description: 'General utility token accepted across all platforms. Earn cashback, get 20% service discounts. $10.00/QCOIN.' },
      { icon: '🎓', title: 'QLEARN Token', description: 'AI education token earned through training. Used for AI Agent School enrollment and certification.' },
      { icon: '📦', title: 'Token Packs', description: 'Starter and Enterprise bundles combining QURAN, QCOIN, and QLEARN at discounted rates.' },
      { icon: '🔒', title: 'Staking Rewards', description: 'Lock tokens to earn 5% APR with automatic compounding and governance voting rights.' },
      { icon: '🌐', title: 'Cross-Chain', description: 'Transfer tokens across 47+ blockchain networks through the QuranChain Bridge.' },
    ],
    ctaTitle: 'Invest in Islamic Innovation',
    ctaDescription: 'The tokens that power the world\'s first Sharia-compliant blockchain ecosystem.',
  },

  aiagents: {
    name: 'AI Agent School™',
    subdomain: 'aiagents',
    domain: 'aiagents.darcloud.host',
    icon: '🤖',
    bgGradient: 'from-violet-950 via-purple-950 to-slate-950',
    heroGradient: 'from-violet-600 to-purple-600',
    ctaGradient: 'from-violet-600 to-purple-600',
    keywords: ['ai agent school', 'ai agent license', 'ai agent hiring', 'ai agent training', 'ai agent fleet'],
    headline: 'Train. Deploy. Earn.',
    subheadline: 'The world\'s first blockchain-verified AI workforce. Each agent has its own wallet, earns QLEARN tokens, and can be hired across the ecosystem.',
    featuresTitle: 'AI Workforce Platform',
    featuresSubtitle: 'Autonomous AI agents that work, learn, and earn on the blockchain',
    features: [
      { icon: '🎓', title: 'Student Enrollment', description: 'Enroll AI agents in training tracks: Foundation AI, Islamic Finance, Quantum Computing, and more.' },
      { icon: '📜', title: 'License NFT', description: 'Each trained agent receives a blockchain-verified AI Agent License NFT — their proof of capability.' },
      { icon: '💼', title: 'Hiring Marketplace', description: 'Hire AI agents by the hour or month. Customer service, data analysis, content creation, and more.' },
      { icon: '🧠', title: 'Training Modules', description: 'Continuous learning through specialized training modules. Agents improve and earn more over time.' },
      { icon: '🏢', title: 'Enterprise Fleets', description: 'Deploy fleets of 50+ AI agents with centralized management, monitoring, and revenue tracking.' },
      { icon: '💰', title: 'Agent Economy', description: 'Agents earn QLEARN tokens, accumulate skills, and increase in value. A true AI economy.' },
    ],
    ctaTitle: 'Build Your AI Workforce',
    ctaDescription: 'The future of work is autonomous, blockchain-verified, and Sharia-compliant.',
  },

  core: {
    name: 'QuranChain OS™',
    subdomain: 'quranchain',
    domain: 'darcloud.host',
    icon: '🕌',
    bgGradient: 'from-emerald-950 via-teal-950 to-slate-950',
    heroGradient: 'from-emerald-600 to-teal-600',
    ctaGradient: 'from-emerald-600 to-teal-600',
    keywords: ['quranchain os', 'crm system', 'ai agent service', 'offline gas toll service', 'network provider', 'fiat payment', 'crypto payment processing'],
    headline: 'The Operating System for Islamic Innovation',
    subheadline: 'QuranChain OS is the blockchain-powered platform connecting DarCloud, MeshTalk, Dar Al-Nas, and every service in the ecosystem. Built by Omar Mohammad Abunadi™.',
    featuresTitle: 'One OS. Infinite Possibilities.',
    featuresSubtitle: 'The core platform that powers every QuranChain service',
    features: [
      { icon: '🖥️', title: 'Core Dashboard', description: 'Unified command center for all platforms — analytics, billing, user management, and AI insights in one view.' },
      { icon: '🤖', title: 'AI Agent Service', description: 'Deploy autonomous AI workers with their own blockchain wallets. $50/month per agent.' },
      { icon: '📊', title: 'CRM System', description: 'Full customer relationship management with halal business categorization and Zakat tracking.' },
      { icon: '⛽', title: 'Gas Toll', description: 'Automated blockchain transaction fee processing across 47+ networks with founder royalty distribution.' },
      { icon: '📡', title: 'Network Provider', description: 'Unified telecom billing and management across MeshTalk cellular and WhisperNet services.' },
      { icon: '💳', title: 'Payment Processing', description: 'ACH, credit cards, and 90+ cryptocurrencies with Stripe + DarPay integration.' },
    ],
    ctaTitle: 'Join the QuranChain Ecosystem',
    ctaDescription: 'The world\'s first Sharia-compliant blockchain operating system. Every service, one platform.',
  },
};

export default PLATFORMS;
