# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║  PROPRIETARY AND CONFIDENTIAL — ALL RIGHTS RESERVED                         ║
# ║  © 2024-2026 Omar Mohammad Abunadi™ | QuranChain™                           ║
# ║  Immutable Founder Royalty: 30% · License: See /LICENSE                      ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝
apiVersion: v1
kind: Service
metadata:
  name: quranchain-service
spec:
  type: LoadBalancer
  selector:
    app: quranchain
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP