# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║  PROPRIETARY AND CONFIDENTIAL — ALL RIGHTS RESERVED                         ║
# ║  © 2024-2026 Omar Mohammad Abunadi™ | QuranChain™                           ║
# ║  Immutable Founder Royalty: 30% · License: See /LICENSE                      ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝
name = "darcloud-blockchain"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "3bfc21f5baba642160ec706818e3a19f"

[vars]
ENVIRONMENT = "production"
ORIGIN_URL = "http://localhost:3001"

workers_dev = true

[[routes]]
pattern = "blockchain.darcloud.host/*"
zone_name = "darcloud.host"

[[routes]]
pattern = "chain.darcloud.host/*"
zone_name = "darcloud.host"

[[routes]]
pattern = "explorer.darcloud.host/*"
zone_name = "darcloud.host"
